clear;
clc;
x=readtable("../precios_monteria.csv");
y=x.PROMEDIO;
figure(1)
plot(x.FECHA,x.PROMEDIO) 
% Decompose signal using the EMD

% Generated by MATLAB(R) 23.2 and Wavelet Toolbox 23.2.
% Generated on: 01-Mar-2024 10:56:16

% Logical array for selecting reconstruction elements
levelForReconstruction = [true,true,true,true,true,true];

% Perform the decomposition using EMD
[imf,residual,info] = emd(y, ...
    SiftRelativeTolerance=0.2, ...
    SiftMaxIterations=100, ...
    MaxNumIMF=2, ...
    MaxNumExtrema=1, ...
    MaxEnergyRatio=20, ...
    Interpolation='spline');

% Construct MRA matrix by appending IMFs and residual
mra = [imf residual].';


figure(2)
t = tiledlayout(2,3, ...
    TileSpacing="compact",Padding="compact");
for n = 1:2
    nexttile(t)
    plot(x.FECHA,imf(:,n))
    title("Modo " + num2str(n))
    xlabel("Tiempo")

    fecha_formateada=datestr(x.FECHA, 'yyyy-mm-dd');
    Modo=table(fecha_formateada,imf(:,n),'VariableNames',{'FECHA','PROMEDIO'});
    writetable(Modo,"" + ...
    "descomposicion_monteria/Modo_" + num2str(n)+".csv")
end

nexttile(t)
plot(x.FECHA,residual(:,1))
title('Residuo')
xlabel("Tiempo");
title(t,"Empirical Mode Decomposition (EMD)")
%saveas(gcf, 'imagenes/Descompocision_EMD_matrix');

fecha_formateada=datestr(x.FECHA, 'yyyy-mm-dd');
    tabla_residuo=table(fecha_formateada,residual(:,1),'VariableNames',{'FECHA','PROMEDIO'});
    writetable(tabla_residuo,"" + ...
    "descomposicion_monteria/Residuo.csv")

% Sum down the rows of the selected multiresolution signals
y2 = sum(imf(:,1:2),2)+residual;
figure(3)
plot(x.FECHA,y2, 'Color', 'r')
title("Reconstruccion EMD")
;